# Generated by Django 3.1.1 on 2020-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('gender', models.CharField(max_length=16, verbose_name='性别')),
                ('tel', models.CharField(max_length=16, unique=True, verbose_name='电话号码')),
            ],
            options={
                'verbose_name': '用户信息表',
            },
        ),
    ]
