# Generated by Django 3.1.1 on 2020-09-28 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineId', models.CharField(max_length=32, unique=True, verbose_name='药物编号')),
                ('medicineName', models.CharField(max_length=128, verbose_name='药物名称')),
                ('description', models.CharField(max_length=512, verbose_name='药物描述')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.datetime(2020, 9, 28, 11, 25, 2, 821176, tzinfo=utc), verbose_name='出生日期'),
        ),
    ]
