# Generated by Django 3.1 on 2020-10-04 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dh', '0002_auto_20200928_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.datetime(2020, 10, 4, 14, 51, 32, 358928, tzinfo=utc), verbose_name='出生日期'),
        ),
    ]
